language: node_js
  - 9
  - 8
dist: trusty
sudo: false

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules